# Generated by Django 4.2.3 on 2023-07-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_detail',
            name='enrollment_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
