# Generated by Django 4.2.3 on 2023-07-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_alter_academic_detail_enrollment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_detail',
            name='enrollment_id',
        ),
    ]
